services:
  nextjs:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - redis
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - firstpromoter-dashboard
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - firstpromoter-dashboard
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

volumes:
  redis_data:

networks:
  firstpromoter-dashboard:
    driver: bridge
